#!/bin/bash

POKEMON_LIST="bulbasaur ivysaur venusaur charmander charmeleon"

echo "" > errors.txt

for pokemon in $POKEMON_LIST
do
    echo "Fetching data for $pokemon..."
    attempt=1
    success=0

    while [ $attempt -le 3 ]; do
        echo "Attempt $attempt for $pokemon..."

    curl -s "https://pokeapi.co/api/v2/pokemon/$pokemon" -o "${pokemon}.json"

    if [ $? -eq 0 ]; then
        echo "Successfully fetched $pokemon"
        success=1
        break
    fi

    attempt=$((attempt + 1))
    sleep 1
done

if [ $? -ne 1 ]; then
    echo "Failed to fetch $pokemon Logging error..."
    echo "Error fetching $pokemon" >> errors.txt
    rm -f "${pokemon}.json"
fi

    sleep 1
done