#!/bin/bash

POKEMON_LIST="bulbasaur ivysaur venusaur charmander charmeleon"

for pokemon in $POKEMON_LIST
do
    echo "Fetching data for $pokemon..."

    curl -s "https://pokeapi.co/api/v2/pokemon/$pokemon" -o "${pokemon}.json"

    if [ $? -ne 0 ]; then
        echo "Error fetching $pokemon" >> errors.txt
    fi

    sleep 1
done