#!/bin/bash

#Extracting files using jq
NAME=$(jq -r '.name' data.json)
HEIGHT=$(jq -r '.height' data.json)
WEIGHT=$(jq -r '.weight' data.json)
TYPE=$(jq -r '.type' data.json)

#Conversion of height and weight
HEIGHT_M=$(awk "BEGIN{printf \"%.1f\", $HEIGHT/10}")
WEIGHT_KG=$(awk "BEGIN {printf \"%.1f\", $WEIGHT/10}")

NAME_CAP="${NAME^}"
TYPE_CAP="${TYPE^}"
echo "$NAME_CAP is of type $TYPE_CAP, weighs ${WEIGHT_KG}kg, and is ${HEIGHT_M}m tall."