#!/bin/bash

#Extracting files using jq
name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
height=$(jq -r '.height' data.json | sed 's/.*/\u&/')
weight=$(jq -r '.weight' data.json | sed 's/./\u&/')
type=$(jq -r '.type' data.json | sed 's/.*/\u&/')

#Conversion of height and weight
formatted_height=$(awk "BEGIN{printf \"%.1f\", $height/10}")
formatted_weight=$(awk "BEGIN {printf \"%.1f\", $weight/10}")

echo "$name is of type $type weighs ${formatted_weight}kg, and is ${formatted_height}m tall."